import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  ManyToOne,
  JoinColumn,
  CreateDateColumn,
  UpdateDateColumn,
  Index,
} from 'typeorm';
import { RegulatoryAnnouncement } from './announcement.model';
import { PIL } from './pil.model';
import { User } from './user.model';

export type VariationStatus = 'pending_review' | 'approved' | 'rejected' | 'draft_generated';
export type AffectedSectionType = 'dosage' | 'contraindications' | 'adverse_events' | 'warnings' | 'precautions' | 'interactions' | 'other';

export interface SectionDiff {
  sectionType: AffectedSectionType;
  sectionName: string;
  currentText: string;
  requiredText: string;
  diffHighlights: DiffHighlight[];
  confidence: number; // 0-100
  requiresUpdate: boolean;
}

export interface DiffHighlight {
  type: 'addition' | 'deletion' | 'modification';
  startIndex: number;
  endIndex: number;
  originalText?: string;
  newText?: string;
}

export interface VariationMetadata {
  nlpConfidence: number;
  processingTime: number; // milliseconds
  diffAlgorithm: string; // e.g., 'myers', 'patience'
  autoGeneratedDraft: boolean;
  reviewerNotes?: string;
}

@Entity('variations')
@Index(['announcementId', 'pilId'])
@Index(['status'])
@Index(['createdAt'])
export class Variation {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ name: 'announcement_id' })
  announcementId: number;

  @ManyToOne(() => RegulatoryAnnouncement)
  @JoinColumn({ name: 'announcement_id' })
  announcement: RegulatoryAnnouncement;

  @Column({ name: 'pil_id' })
  pilId: number;

  @ManyToOne(() => PIL)
  @JoinColumn({ name: 'pil_id' })
  pil: PIL;

  @Column({
    type: 'varchar',
    length: 20,
    default: 'pending_review',
  })
  status: VariationStatus;

  @Column({ type: 'jsonb' })
  affectedSections: SectionDiff[];

  @Column({ type: 'text', nullable: true })
  draftPILPath: string | null; // S3 path to auto-generated draft PIL

  @Column({ type: 'text', nullable: true })
  diffReportPath: string | null; // S3 path to detailed diff report PDF

  @Column({ type: 'numeric', precision: 5, scale: 2 })
  overallConfidence: number; // 0-100, weighted average of section confidences

  @Column({ type: 'jsonb' })
  metadata: VariationMetadata;

  @Column({ name: 'reviewed_by', nullable: true })
  reviewedBy: number | null;

  @ManyToOne(() => User, { nullable: true })
  @JoinColumn({ name: 'reviewed_by' })
  reviewer: User | null;

  @Column({ type: 'timestamptz', nullable: true })
  reviewedAt: Date | null;

  @Column({ type: 'text', nullable: true })
  reviewComments: string | null;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt: Date;
}