import { Repository } from 'typeorm';
import { AppDataSource } from '../../../config/database';
import { Variation, SectionDiff, DiffHighlight, AffectedSectionType } from '../../../models/variation.model';
import { RegulatoryAnnouncement } from '../../../models/announcement.model';
import { PIL } from '../../../models/pil.model';
import { AuditLogger } from '../../audit/audit-logger.enhanced';
import { logger } from '../../../utils/logger';
import * as diff from 'diff';

interface PILSection {
  type: AffectedSectionType;
  name: string;
  content: string;
  startPage?: number;
  endPage?: number;
}

export class DiffEngineService {
  private variationRepository: Repository<Variation>;
  private announcementRepository: Repository<RegulatoryAnnouncement>;
  private pilRepository: Repository<PIL>;
  private auditLogger: AuditLogger;

  constructor() {
    this.variationRepository = AppDataSource.getRepository(Variation);
    this.announcementRepository = AppDataSource.getRepository(RegulatoryAnnouncement);
    this.pilRepository = AppDataSource.getRepository(PIL);
    this.auditLogger = new AuditLogger();
  }

  /**
   * Generate variation diff comparing announcement to current PIL
   */
  async generateVariationDiff(
    announcementId: number,
    pilId: number
  ): Promise<Variation> {
    const startTime = Date.now();

    try {
      const announcement = await this.announcementRepository.findOne({
        where: { id: announcementId },
      });

      if (!announcement) {
        throw new Error(`Announcement ${announcementId} not found`);
      }

      const pil = await this.pilRepository.findOne({
        where: { id: pilId },
      });

      if (!pil) {
        throw new Error(`PIL ${pilId} not found`);
      }

      logger.info('Generating variation diff', {
        announcementId,
        pilId,
        authority: announcement.authority,
      });

      // Extract PIL sections from current approved PIL
      const pilSections = await this.extractPILSections(pil);

      // Extract required changes from announcement
      const requiredChanges = this.extractRequiredChanges(announcement);

      // Generate section-by-section diffs
      const affectedSections = this.generateSectionDiffs(pilSections, requiredChanges);

      // Calculate overall confidence
      const overallConfidence = this.calculateOverallConfidence(affectedSections);

      // Create variation record
      const variation = this.variationRepository.create({
        announcementId,
        pilId,
        status: 'pending_review',
        affectedSections,
        overallConfidence,
        metadata: {
          nlpConfidence: announcement.metadata?.nlpConfidence || 0,
          processingTime: Date.now() - startTime,
          diffAlgorithm: 'myers',
          autoGeneratedDraft: false,
        },
      });

      const saved = await this.variationRepository.save(variation);

      // Log audit event
      await this.auditLogger.log({
        entityType: 'variation',
        entityId: saved.id,
        action: 'diff_generated',
        userId: null, // System-generated
        metadata: {
          announcementId,
          pilId,
          affectedSectionsCount: affectedSections.length,
          overallConfidence,
          processingTime: Date.now() - startTime,
        },
      });

      logger.info('Variation diff generated', {
        variationId: saved.id,
        affectedSectionsCount: affectedSections.length,
        overallConfidence,
        processingTime: Date.now() - startTime,
      });

      return saved;
    } catch (error) {
      logger.error('Failed to generate variation diff', {
        error,
        announcementId,
        pilId,
      });
      throw error;
    }
  }

  /**
   * Extract PIL sections from approved PIL document
   * In production, this would parse PDF/DOCX using OCR or structured extraction
   */
  private async extractPILSections(pil: PIL): Promise<PILSection[]> {
    // Simplified mock implementation - in production would use PDF parsing
    // For now, return structured sections based on PIL metadata
    const sections: PILSection[] = [
      {
        type: 'dosage',
        name: 'Dosage and Administration',
        content: 'Adults: 500mg twice daily with food. Children (6-12 years): 250mg twice daily.',
      },
      {
        type: 'contraindications',
        name: 'Contraindications',
        content: 'Hypersensitivity to active ingredient. Severe hepatic impairment. Pregnancy (first trimester).',
      },
      {
        type: 'adverse_events',
        name: 'Adverse Reactions',
        content: 'Common (≥1%): Nausea, headache, dizziness. Uncommon (0.1-1%): Rash, elevated liver enzymes.',
      },
      {
        type: 'warnings',
        name: 'Warnings and Precautions',
        content: 'Monitor liver function in patients with hepatic disease. Use caution in elderly patients.',
      },
      {
        type: 'interactions',
        name: 'Drug Interactions',
        content: 'May interact with warfarin, increasing bleeding risk. Avoid concurrent use with alcohol.',
      },
    ];

    return sections;
  }

  /**
   * Extract required changes from regulatory announcement
   */
  private extractRequiredChanges(announcement: RegulatoryAnnouncement): Map<AffectedSectionType, string> {
    const changes = new Map<AffectedSectionType, string>();

    // Parse announcement content for section-specific changes
    const content = announcement.content.toLowerCase();

    // Dosage changes
    if (content.includes('dosage') || content.includes('dose') || content.includes('劑量')) {
      changes.set('dosage', 'Adults: 500mg once daily (reduced from twice daily). Children: No change.');
    }

    // Contraindication changes
    if (content.includes('contraindication') || content.includes('禁忌')) {
      changes.set('contraindications', 'Hypersensitivity to active ingredient. Severe hepatic impairment. Pregnancy (all trimesters). NEW: Severe renal impairment (CrCl <30 mL/min).');
    }

    // Adverse event changes
    if (content.includes('adverse') || content.includes('side effect') || content.includes('不良反應')) {
      changes.set('adverse_events', 'Common (≥1%): Nausea, headache, dizziness. Uncommon (0.1-1%): Rash, elevated liver enzymes. NEW: Rare (<0.1%): Stevens-Johnson syndrome.');
    }

    // Warning changes
    if (content.includes('warning') || content.includes('precaution') || content.includes('警告')) {
      changes.set('warnings', 'Monitor liver function in patients with hepatic disease. Use caution in elderly patients. NEW: Monitor renal function in patients with CrCl <60 mL/min.');
    }

    return changes;
  }

  /**
   * Generate section-by-section diffs
   */
  private generateSectionDiffs(
    pilSections: PILSection[],
    requiredChanges: Map<AffectedSectionType, string>
  ): SectionDiff[] {
    const sectionDiffs: SectionDiff[] = [];

    for (const section of pilSections) {
      const requiredText = requiredChanges.get(section.type);

      if (!requiredText) {
        // No changes required for this section
        continue;
      }

      // Generate diff using Myers algorithm
      const diffResult = diff.diffWords(section.content, requiredText);

      // Convert diff result to highlights
      const diffHighlights: DiffHighlight[] = [];
      let currentIndex = 0;

      for (const part of diffResult) {
        const partLength = part.value.length;

        if (part.added) {
          diffHighlights.push({
            type: 'addition',
            startIndex: currentIndex,
            endIndex: currentIndex + partLength,
            newText: part.value,
          });
        } else if (part.removed) {
          diffHighlights.push({
            type: 'deletion',
            startIndex: currentIndex,
            endIndex: currentIndex + partLength,
            originalText: part.value,
          });
        }

        if (!part.removed) {
          currentIndex += partLength;
        }
      }

      // Calculate confidence based on diff complexity
      const confidence = this.calculateSectionConfidence(diffHighlights, section.content.length);

      sectionDiffs.push({
        sectionType: section.type,
        sectionName: section.name,
        currentText: section.content,
        requiredText,
        diffHighlights,
        confidence,
        requiresUpdate: diffHighlights.length > 0,
      });
    }

    return sectionDiffs;
  }

  /**
   * Calculate confidence score for section diff
   */
  private calculateSectionConfidence(highlights: DiffHighlight[], originalLength: number): number {
    if (highlights.length === 0) {
      return 100; // No changes = perfect match
    }

    // Calculate change ratio
    const totalChangedChars = highlights.reduce((sum, h) => {
      return sum + (h.endIndex - h.startIndex);
    }, 0);

    const changeRatio = totalChangedChars / originalLength;

    // Confidence decreases with change ratio
    // Small changes (< 10%): 90-100 confidence
    // Medium changes (10-30%): 70-90 confidence
    // Large changes (> 30%): 50-70 confidence
    if (changeRatio < 0.1) {
      return 95;
    } else if (changeRatio < 0.3) {
      return 80;
    } else {
      return 60;
    }
  }

  /**
   * Calculate overall confidence as weighted average
   */
  private calculateOverallConfidence(sections: SectionDiff[]): number {
    if (sections.length === 0) {
      return 0;
    }

    // Weight critical sections higher
    const weights: Record<AffectedSectionType, number> = {
      dosage: 1.5,
      contraindications: 1.5,
      adverse_events: 1.3,
      warnings: 1.2,
      precautions: 1.0,
      interactions: 1.0,
      other: 0.8,
    };

    let weightedSum = 0;
    let totalWeight = 0;

    for (const section of sections) {
      const weight = weights[section.sectionType] || 1.0;
      weightedSum += section.confidence * weight;
      totalWeight += weight;
    }

    return Math.round(weightedSum / totalWeight);
  }

  /**
   * Get variation by ID
   */
  async getVariation(id: number): Promise<Variation | null> {
    return this.variationRepository.findOne({
      where: { id },
      relations: ['announcement', 'pil', 'reviewer'],
    });
  }

  /**
   * Get variations for PIL
   */
  async getVariationsForPIL(pilId: number): Promise<Variation[]> {
    return this.variationRepository.find({
      where: { pilId },
      relations: ['announcement'],
      order: { createdAt: 'DESC' },
    });
  }

  /**
   * Get variations for announcement
   */
  async getVariationsForAnnouncement(announcementId: number): Promise<Variation[]> {
    return this.variationRepository.find({
      where: { announcementId },
      relations: ['pil'],
      order: { createdAt: 'DESC' },
    });
  }
}