import { Repository } from 'typeorm';
import { AppDataSource } from '../../../config/database';
import { Variation, SectionDiff } from '../../../models/variation.model';
import { PIL } from '../../../models/pil.model';
import { AuditLogger } from '../../audit/audit-logger.enhanced';
import { logger } from '../../../utils/logger';
import { S3Service } from '../../storage/s3.service';
import * as PDFDocument from 'pdfkit';
import { Readable } from 'stream';

interface DraftPILOptions {
  includeTrackChanges: boolean;
  highlightColor: string;
  generatePDF: boolean;
}

export class DraftGeneratorService {
  private variationRepository: Repository<Variation>;
  private pilRepository: Repository<PIL>;
  private auditLogger: AuditLogger;
  private s3Service: S3Service;

  constructor() {
    this.variationRepository = AppDataSource.getRepository(Variation);
    this.pilRepository = AppDataSource.getRepository(PIL);
    this.auditLogger = new AuditLogger();
    this.s3Service = new S3Service();
  }

  /**
   * Generate draft variation PIL with tracked changes
   */
  async generateDraftPIL(
    variationId: number,
    options: Partial<DraftPILOptions> = {}
  ): Promise<Variation> {
    const startTime = Date.now();

    const defaultOptions: DraftPILOptions = {
      includeTrackChanges: true,
      highlightColor: '#FFD700',
      generatePDF: true,
      ...options,
    };

    try {
      const variation = await this.variationRepository.findOne({
        where: { id: variationId },
        relations: ['pil', 'announcement'],
      });

      if (!variation) {
        throw new Error(`Variation ${variationId} not found`);
      }

      logger.info('Generating draft PIL', {
        variationId,
        pilId: variation.pilId,
        affectedSectionsCount: variation.affectedSections.length,
      });

      // Generate draft content with tracked changes
      const draftContent = this.generateDraftContent(
        variation.affectedSections,
        defaultOptions
      );

      // Generate PDF if requested
      let draftPILPath: string | null = null;
      let diffReportPath: string | null = null;

      if (defaultOptions.generatePDF) {
        draftPILPath = await this.generateDraftPDF(
          variation,
          draftContent,
          defaultOptions
        );

        diffReportPath = await this.generateDiffReportPDF(
          variation,
          draftContent
        );
      }

      // Update variation record
      variation.draftPILPath = draftPILPath;
      variation.diffReportPath = diffReportPath;
      variation.status = 'draft_generated';
      variation.metadata = {
        ...variation.metadata,
        autoGeneratedDraft: true,
        processingTime: Date.now() - startTime,
      };

      const saved = await this.variationRepository.save(variation);

      // Log audit event
      await this.auditLogger.log({
        entityType: 'variation',
        entityId: saved.id,
        action: 'draft_generated',
        userId: null, // System-generated
        metadata: {
          draftPILPath,
          diffReportPath,
          processingTime: Date.now() - startTime,
        },
      });

      logger.info('Draft PIL generated', {
        variationId: saved.id,
        draftPILPath,
        diffReportPath,
        processingTime: Date.now() - startTime,
      });

      return saved;
    } catch (error) {
      logger.error('Failed to generate draft PIL', {
        error,
        variationId,
      });
      throw error;
    }
  }

  /**
   * Generate draft content with tracked changes
   */
  private generateDraftContent(
    affectedSections: SectionDiff[],
    options: DraftPILOptions
  ): Map<string, string> {
    const draftContent = new Map<string, string>();

    for (const section of affectedSections) {
      if (!section.requiresUpdate) {
        draftContent.set(section.sectionName, section.currentText);
        continue;
      }

      if (options.includeTrackChanges) {
        // Generate content with track changes markup
        const markedContent = this.applyTrackChanges(
          section.currentText,
          section.requiredText,
          section.diffHighlights,
          options.highlightColor
        );
        draftContent.set(section.sectionName, markedContent);
      } else {
        // Use required text directly
        draftContent.set(section.sectionName, section.requiredText);
      }
    }

    return draftContent;
  }

  /**
   * Apply track changes markup to text
   */
  private applyTrackChanges(
    currentText: string,
    requiredText: string,
    highlights: any[],
    highlightColor: string
  ): string {
    // For HTML/rich text output
    let markedText = requiredText;

    // Add markup for additions and deletions
    // In production, this would generate proper track changes format
    // For now, using simple HTML-like markup
    for (const highlight of highlights) {
      if (highlight.type === 'addition') {
        markedText = markedText.replace(
          highlight.newText,
          `<ins style="background-color: ${highlightColor};">${highlight.newText}</ins>`
        );
      } else if (highlight.type === 'deletion') {
        markedText = markedText.replace(
          highlight.originalText,
          `<del style="text-decoration: line-through; color: red;">${highlight.originalText}</del>`
        );
      }
    }

    return markedText;
  }

  /**
   * Generate draft PIL PDF with tracked changes
   */
  private async generateDraftPDF(
    variation: Variation,
    draftContent: Map<string, string>,
    options: DraftPILOptions
  ): Promise<string> {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks: Buffer[] = [];

    // Collect PDF chunks
    doc.on('data', (chunk) => chunks.push(chunk));

    // Header
    doc.fontSize(20).text('Draft Variation PIL', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(`Product: ${variation.pil.productName}`);
    doc.text(`Market: ${variation.pil.market}`);
    doc.text(`Variation ID: ${variation.id}`);
    doc.text(`Generated: ${new Date().toISOString()}`);
    doc.moveDown(2);

    // Sections
    for (const [sectionName, content] of draftContent.entries()) {
      doc.fontSize(16).text(sectionName, { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11).text(content, { align: 'justify' });
      doc.moveDown(2);
    }

    // Footer
    doc.fontSize(10).text(
      'This is an auto-generated draft. Requires regulatory specialist review before submission.',
      { align: 'center', color: 'red' }
    );

    doc.end();

    // Wait for PDF generation to complete
    await new Promise((resolve) => doc.on('end', resolve));

    const pdfBuffer = Buffer.concat(chunks);

    // Upload to S3
    const s3Key = `variations/${variation.id}/draft-pil-${Date.now()}.pdf`;
    await this.s3Service.uploadFile(s3Key, pdfBuffer, 'application/pdf');

    return s3Key;
  }

  /**
   * Generate detailed diff report PDF
   */
  private async generateDiffReportPDF(
    variation: Variation,
    draftContent: Map<string, string>
  ): Promise<string> {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk) => chunks.push(chunk));

    // Header
    doc.fontSize(20).text('Variation Difference Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(`Product: ${variation.pil.productName}`);
    doc.text(`Announcement: ${variation.announcement.announcementId}`);
    doc.text(`Overall Confidence: ${variation.overallConfidence}%`);
    doc.moveDown(2);

    // Affected sections summary
    doc.fontSize(16).text('Affected Sections', { underline: true });
    doc.moveDown(0.5);

    for (const section of variation.affectedSections) {
      doc.fontSize(14).text(`${section.sectionName} (${section.confidence}% confidence)`);
      doc.moveDown(0.3);

      doc.fontSize(11).text('Current:', { underline: true });
      doc.text(section.currentText, { color: 'gray' });
      doc.moveDown(0.5);

      doc.fontSize(11).text('Required:', { underline: true });
      doc.text(section.requiredText, { color: 'blue' });
      doc.moveDown(1.5);
    }

    doc.end();

    await new Promise((resolve) => doc.on('end', resolve));

    const pdfBuffer = Buffer.concat(chunks);

    // Upload to S3
    const s3Key = `variations/${variation.id}/diff-report-${Date.now()}.pdf`;
    await this.s3Service.uploadFile(s3Key, pdfBuffer, 'application/pdf');

    return s3Key;
  }

  /**
   * Approve variation analysis
   */
  async approveVariation(
    variationId: number,
    userId: number,
    comments?: string
  ): Promise<Variation> {
    const variation = await this.variationRepository.findOne({
      where: { id: variationId },
    });

    if (!variation) {
      throw new Error(`Variation ${variationId} not found`);
    }

    variation.status = 'approved';
    variation.reviewedBy = userId;
    variation.reviewedAt = new Date();
    variation.reviewComments = comments || null;

    const saved = await this.variationRepository.save(variation);

    await this.auditLogger.log({
      entityType: 'variation',
      entityId: saved.id,
      action: 'approved',
      userId,
      metadata: { comments },
    });

    logger.info('Variation approved', { variationId, userId });

    return saved;
  }

  /**
   * Reject variation analysis
   */
  async rejectVariation(
    variationId: number,
    userId: number,
    comments: string
  ): Promise<Variation> {
    const variation = await this.variationRepository.findOne({
      where: { id: variationId },
    });

    if (!variation) {
      throw new Error(`Variation ${variationId} not found`);
    }

    variation.status = 'rejected';
    variation.reviewedBy = userId;
    variation.reviewedAt = new Date();
    variation.reviewComments = comments;

    const saved = await this.variationRepository.save(variation);

    await this.auditLogger.log({
      entityType: 'variation',
      entityId: saved.id,
      action: 'rejected',
      userId,
      metadata: { comments },
    });

    logger.info('Variation rejected', { variationId, userId, comments });

    return saved;
  }
}