import { DraftGeneratorService } from '../../../src/services/variation/draft-generator/draft-generator.service';
import { DiffEngineService } from '../../../src/services/variation/diff-engine/diff-engine.service';
import { AppDataSource } from '../../../src/config/database';
import { Variation } from '../../../src/models/variation.model';
import { RegulatoryAnnouncement } from '../../../src/models/announcement.model';
import { PIL } from '../../../src/models/pil.model';
import { User } from '../../../src/models/user.model';

jest.mock('../../../src/services/audit/audit-logger.enhanced');
jest.mock('../../../src/services/storage/s3.service');

describe('DraftGeneratorService', () => {
  let service: DraftGeneratorService;
  let diffEngine: DiffEngineService;
  let variationRepository: any;
  let announcementRepository: any;
  let pilRepository: any;
  let userRepository: any;

  beforeAll(async () => {
    await AppDataSource.initialize();
  });

  afterAll(async () => {
    await AppDataSource.destroy();
  });

  beforeEach(() => {
    service = new DraftGeneratorService();
    diffEngine = new DiffEngineService();
    variationRepository = AppDataSource.getRepository(Variation);
    announcementRepository = AppDataSource.getRepository(RegulatoryAnnouncement);
    pilRepository = AppDataSource.getRepository(PIL);
    userRepository = AppDataSource.getRepository(User);
  });

  describe('generateDraftPIL', () => {
    it('should generate draft PIL with tracked changes', async () => {
      // Create test data
      const announcement = announcementRepository.create({
        authority: 'TFDA',
        announcementId: 'TFDA-2024-DRAFT-001',
        publishedAt: new Date(),
        affectedProducts: ['Product E'],
        sourceUrl: 'https://tfda.gov.tw/announcement/draft-001',
        content: 'New contraindication required.',
        metadata: { nlpConfidence: 90 },
      });
      await announcementRepository.save(announcement);

      const pil = pilRepository.create({
        productName: 'Product E',
        market: 'TFDA',
        status: 'approved',
        sourceType: 'innovator',
      });
      await pilRepository.save(pil);

      // Generate variation diff first
      const variation = await diffEngine.generateVariationDiff(announcement.id, pil.id);

      // Generate draft PIL
      const draft = await service.generateDraftPIL(variation.id);

      expect(draft).toBeDefined();
      expect(draft.status).toBe('draft_generated');
      expect(draft.draftPILPath).toBeDefined();
      expect(draft.diffReportPath).toBeDefined();
      expect(draft.metadata.autoGeneratedDraft).toBe(true);
    });

    it('should update variation status to draft_generated', async () => {
      const announcement = announcementRepository.create({
        authority: 'TFDA',
        announcementId: 'TFDA-2024-DRAFT-002',
        publishedAt: new Date(),
        affectedProducts: ['Product F'],
        sourceUrl: 'https://tfda.gov.tw/announcement/draft-002',
        content: 'Dosage adjustment required.',
        metadata: { nlpConfidence: 88 },
      });
      await announcementRepository.save(announcement);

      const pil = pilRepository.create({
        productName: 'Product F',
        market: 'TFDA',
        status: 'approved',
        sourceType: 'innovator',
      });
      await pilRepository.save(pil);

      const variation = await diffEngine.generateVariationDiff(announcement.id, pil.id);
      expect(variation.status).toBe('pending_review');

      const draft = await service.generateDraftPIL(variation.id);
      expect(draft.status).toBe('draft_generated');
    });
  });

  describe('approveVariation', () => {
    it('should approve variation and record reviewer', async () => {
      // Create user
      const user = userRepository.create({
        email: 'reviewer@lotus.com',
        fullName: 'Test Reviewer',
        role: 'Regulatory_Reviewer',
        isActive: true,
      });
      await userRepository.save(user);

      // Create variation
      const announcement = announcementRepository.create({
        authority: 'TFDA',
        announcementId: 'TFDA-2024-APPROVE-001',
        publishedAt: new Date(),
        affectedProducts: ['Product G'],
        sourceUrl: 'https://tfda.gov.tw/announcement/approve-001',
        content: 'Variation for approval test.',
        metadata: { nlpConfidence: 92 },
      });
      await announcementRepository.save(announcement);

      const pil = pilRepository.create({
        productName: 'Product G',
        market: 'TFDA',
        status: 'approved',
        sourceType: 'innovator',
      });
      await pilRepository.save(pil);

      const variation = await diffEngine.generateVariationDiff(announcement.id, pil.id);

      // Approve variation
      const approved = await service.approveVariation(
        variation.id,
        user.id,
        'Variation analysis looks correct'
      );

      expect(approved.status).toBe('approved');
      expect(approved.reviewedBy).toBe(user.id);
      expect(approved.reviewedAt).toBeDefined();
      expect(approved.reviewComments).toBe('Variation analysis looks correct');
    });
  });

  describe('rejectVariation', () => {
    it('should reject variation with mandatory comments', async () => {
      const user = userRepository.create({
        email: 'reviewer2@lotus.com',
        fullName: 'Test Reviewer 2',
        role: 'Regulatory_Reviewer',
        isActive: true,
      });
      await userRepository.save(user);

      const announcement = announcementRepository.create({
        authority: 'TFDA',
        announcementId: 'TFDA-2024-REJECT-001',
        publishedAt: new Date(),
        affectedProducts: ['Product H'],
        sourceUrl: 'https://tfda.gov.tw/announcement/reject-001',
        content: 'Variation for rejection test.',
        metadata: { nlpConfidence: 75 },
      });
      await announcementRepository.save(announcement);

      const pil = pilRepository.create({
        productName: 'Product H',
        market: 'TFDA',
        status: 'approved',
        sourceType: 'innovator',
      });
      await pilRepository.save(pil);

      const variation = await diffEngine.generateVariationDiff(announcement.id, pil.id);

      // Reject variation
      const rejected = await service.rejectVariation(
        variation.id,
        user.id,
        'Confidence too low, requires manual review'
      );

      expect(rejected.status).toBe('rejected');
      expect(rejected.reviewedBy).toBe(user.id);
      expect(rejected.reviewedAt).toBeDefined();
      expect(rejected.reviewComments).toBe('Confidence too low, requires manual review');
    });
  });
});